### ISSUE TITLE
Unreliable in some cases. Gets blocked behind readpipe.recv()

### ISSUE THREAD

**Issue by aliqandil** [akindofyoga/asyncio-pipe#2]
Well I'm not actually using this package in my project since I needed a duplex pipe, but I took the idea of adding a reader to the loop and setting an event on it's callback.

Long story short, the method is not reliable enough in some rare cases where too many "send"s are called from the other process, too fast. It might set the event twice, but still block on recv! 

This is how I fixed it in my code, switched to Queue and added the recv call, inside the callback:

```
async def iter_device_reports( self ):
	loop = asyncio.get_event_loop()
	new_msg   = asyncio.Queue()
	read_pipe = self.duplex[0]

	def queue_msg(): new_msg.put_nowait( read_pipe.recv() )
	loop.add_reader( read_pipe.fileno(), queue_msg )

	while True:
		print("Waiting...")
		msg = await new_msg.get()
		print("Got:", msg)
		if not msg: break
		yield msg
```

**Comment by akindofyoga** [comment]
Thanks for bringing this up! I didn't think about multiple writes happening before one recv. 

I fixed this by returning immediately if there is data available, rather than always waiting on the event.
