### ISSUE TITLE
Possible deadlock when using loop.add_reader to read from multiprocessing.Pipe

### ISSUE THREAD

**Issue by valq7711** [akindofyoga/asyncio-pipe#3]
Hi! I came across your awesome project while trying to solve a deadlock issue related to usage `loop.add_reader` + `Connection` (pipe-end of `multiprocessing.Pipe`) I was having. 

1.  `@L18` missing `await` (should be `await self._event.wait()`)
https://github.com/akindofyoga/asyncio-pipe/blob/fd3e6d7313fbdcfd288e0c0835f296a7ec8260ae/src/asyncio_pipe/__init__.py#L15-L22

2. But the fix above does not solve my issue, to see the problem just try this:
```python
async def recv(self): 
     """Receive a (picklable) object""" 
     if not self._connection.poll(): 
         await self._event.wait() 
         if not self._connection.poll(): 
             logger.info('False alarm, no data available, thread will be blocked by recv()')
     result = self._connection.recv()
     self._event.clear() 
     return result 
```

To get deadlock you need to have something like this (i.e. sending task along with reading which are dependent on each other in parent process - recv blocks send, but parent process waits the result from child process and can't send data to child to unblock recv):

```python
async def tick(self):
    loop = asyncio.get_running_loop()
    while True:
        await loop.run_in_executor(self.executor, self._connection.send, 'tick')
        await asyncio.sleep(0.5)
```

In the end of all I solved that this way:
```python
from multiprocessing import connection

async def iter_read_pipe_end(pipe_end: connection.Connection) -> AsyncIterator[Any]:
    data_available = asyncio.Event()
    loop = asyncio.get_running_loop()
    loop.add_reader(pipe_end.fileno(), data_available.set)
    while True:
        while not pipe_end.poll():
            await data_available.wait()
            data_available.clear()
        yield pipe_end.recv()
        data_available.clear()
```

**Comment by akindofyoga** [comment]
Thank you for catching this and proposing a fix! I have just implemented something very similar.
